### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by Just-another-pleb** [bartbutenaers/node-red-contrib-msg-size#2]
Reading the instructions on the page:

>  This node will calculate the seach of each individual message that arrives at the input port.

`seach`    `search`?

Just wondering.

**Comment by bartbutenaers** [comment]
Hi @Just-another-pleb ,
It is fixed now.  I assume you will understand that I won't publish it on NPM as a new version :-).  So it will stay like that on the npm readme page until the next release.
Bart
